name: Build Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: "--max-old-space-size=512"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install
      - run: npm run build